name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build.yml"
      - "buildscripts/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: ['25.11']
        backend: ['tensorrt', 'vllm', 'ort']
        cpuonly: [false, true]
        exclude:
          - backend: tensorrt
            cpuonly: true
    steps:
      -
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Create tag
        run: |
          if [ "${{matrix.backend}}" != "default" ]; then
            tag_suffix="-${{matrix.backend}}"
          else
            tag_suffix=""
          fi

          if [ "${{matrix.cpuonly}}" = "true" ]; then
            tag_suffix="${tag_suffix}-cpuonly"
          fi

          if [ -z "${tag_suffix}" ]; then
            echo "tag= " >> $GITHUB_ENV
          else
            echo "tag=${tag_suffix}" >> $GITHUB_ENV
          fi
      -
        name: Build image
        uses: hieupth/inside-container-action@main
        with:
          shell: bash
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          image: hieupth/namba:${{matrix.release}}
          options: |
            -v ./buildscripts:/buildscripts
            -e NV_VERSION=${{matrix.release}}
            -e BACKEND=${{matrix.backend}}
            -e ENABLE_GPU=${{!matrix.cpuonly}}
          run: |
            /bin/bash /buildscripts/build.sh
      -
        name: Push image
        run: |
          docker tag tritonserver ${{vars.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.release}}${{env.tag}}
          docker push ${{vars.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.release}}${{env.tag}}
