name: GPU

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Builder]
    types: [completed]
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/gpu.yml"
      - "src/gpu.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['24.12', '25.02']
    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build tensorrt image
        uses: docker/build-push-action@v5
        with:
          file: tensorrt.dockerfile
          push: false
          tags: tritonserverbuild:tensorrt-${{matrix.version}}
          build-args: |
            BASE=nvcr.io/nvidia/tensorrt:${{matrix.version}}-py3
      -
        name: Build image
        uses: hieupth/inside-container-action@main
        with: 
          shell: bash
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          image: tritonserverbuild:tensorrt-${{matrix.version}}
          options: |
            -v ./src/gpu.sh:/build.sh
            -e TRITON_VERSION=${{matrix.version}}
          run: |
            mamba install -y cmake psutil && mamba clean -ay
            bash /build.sh
      -
        name: Push image
        run: |
          docker tag tritonserver ${{vars.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.version}}
          docker push ${{vars.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.version}}
